#email to which errors will be sent
email: "pchovanec@lncrna.caltech.edu"
#Location of the config file for barcodeIdentification
bID: "./config.txt"
#Type of SPRITE to analyse: "RNA-DNA" or "DNA-DNA"
type: "RNA-DNA"
#Location of the samples json file produced with fastq2json.py script
samples: "/mnt/data/2019_08_31_Merge_SPRITE_MegaSPRITE_HiSeq_Peter/samples.json"
#output directory
output_dir: "/mnt/data/2019_08_31_Merge_SPRITE_MegaSPRITE_HiSeq_Peter/"
#Currently "mm10","hg19" and "hg38" available
assembly: "mm10"
#Number of barcodes used (this includes DPM/RPM for RNA-DNA)
num_tags: "5"
#Cell type for SNPsplit "psm44" or "psm33"
cell: "psm44"
#Run SNPsplit
snpsplit: "True"
#Aligned for DNA "bowtie2" or "star", if running snpsplit the default is bowtie2
dna_aligner: "bowtie2"
#Aligned for RNA "hisat2" or "star"
rna_aligner: "hisat2"
#Location of STAR aligner indexes
star_index:
    mm10: "/groups/guttman/Peter/genomes/GRCm38.p6/star"
    hg19: "/groups/guttman/genomes/homo_sapiens/hg19/STAR/hg19"
    hg38: "/groups/guttman/Peter/genomes/GRCh38/star"
star_repeat_index:
    mm10: "/groups/guttman/Peter/genomes/ncRNA/star"
    hg19: "/groups/guttman/Peter/genomes/GRCh38/repeats/star"
    hg38: "/groups/guttman/Peter/genomes/GRCh38/repeats/star"
#Annotation GTF file used for featureCounts
anno_gtf:
    mm10: "/groups/guttman/Peter/genomes/GRCm38.p6/GRCm38.p6.annotation.gtf.gz"
    hg19: "/groups/guttman/genomes/homo_sapiens/hg19/STAR/hg19/gencode.v19.annotation.gtf"
    hg38: "/groups/guttman/Peter/genomes/GRCh38/Homo_sapiens.GRCh38.97.gtf.gz"
#Only intron exon annotation
exon_intron_gtf:
    mm10: "/groups/guttman/Peter/genomes/GRCm38.p6/GRCm38.p6.exon_intron.gtf.gz"
#Annotation GTF of rmsk repeats and tRNAs used for featureCounts
anno_repeats_gtf:
    mm10: "/groups/guttman/Peter/genomes/GRCm38.p6/repeats/GRCm38_rmsk_tRNA.gtf.gz"
    hg38: "/groups/guttman/Peter/genomes/GRCh38/repeats/GRCh38_rmsk_TE_all_id.gtf.gz"
#Repeat mask used for filtering DNA contacts
mask:
    mm10: "/groups/guttman/Peter/genomes/GRCm38.p6/blacklist.rmsk.mm10.milliDivLessThan140.bed"
    hg19: "/groups/guttman/genomes/combinations/hg19_mm9/masks/hg19-mm9.gatk35-and-rmsk140.bed"
    hg38: "/groups/guttman/Peter/genomes/GRCh38/hg38_blacklist_rmsk140millidev.bed"
#Other indexes
bowtie2_index:
    mm10: "/groups/guttman/Peter/genomes/GRCm38.p6/GRCm38.p6"
    psm44: "/groups/guttman/Peter/genomes/GRCm38.p6/snpsplit/CAST_EiJ_129S1_SvImJ_dual_hybrid.based_on_GRCm38_N-masked/GRCm38.p6_CAST_EiJ_129S1_SvImj_N-masked"
    psm33: "/groups/guttman/Peter/genomes/GRCm38.p6/snpsplit/C57BL_6NJ_129S1_SvImJ_dual_hybrid.based_on_GRCm38_N-masked/GRCm38.p6_C57BL_6NJ_129S1_SvImJ_N-masked"
    hg38: "/groups/guttman/Peter/genomes/GRCh38/GRCh38"
bowtie2_repeat_index:
    mm10: "/groups/guttman/Peter/genomes/GRCm38.p6/repeats/repetitive_sequences_20190828"
hisat2_index:
    mm10: "/groups/guttman/Peter/genomes/GRCm38.p6/GRCm38.p6"
    hg38: "/groups/guttman/Peter/genomes/GRCh38/GRCh38"
hisat2_splice_sites:
    mm10: "/groups/guttman/Peter/genomes/GRCm38.p6/Mus_musculus.GRCm38.95.ss"
    hg38: "/groups/guttman/Peter/genomes/GRCh38/Homo_sapiens.GRCh38.97.ss"
snp_file:
    psm33: "/groups/guttman/Peter/genomes/GRCm38.p6/snpsplit/all_129S1_SvImJ_SNPs_C57BL_6NJ_reference.based_on_GRCm38.txt"
    psm44: "/groups/guttman/Peter/genomes/GRCm38.p6/snpsplit/all_129S1_SvImJ_SNPs_CAST_EiJ_reference.based_on_GRCm38.txt"
#Used for annotation of cluster file
snp_alleles:
    psm33:
        g1: "C57BL_6NJ"
        g2: "129S1_SvImJ"
    psm44:
        g1: "CAST_EiJ"
        g2: "129S1_SvImJ"
