#Location of the config file for barcodeIdentification
bID:
	"./config.txt"
#Type of SPRITE to analyse: "RNA-DNA" or "DNA-DNA"
type:
	"RNA-DNA"
#Currently "mm10" and "hg19" available
assembly:
	"mm10"
#Number of barcodes used (this includes DPM/RPM for RNA-DNA)
num_tags:
	"5"
#Location of STAR aligner indexes
star_index:
	mm10:
		"/groups/guttman/Peter/genomes/GRCm38.p6/star"
	hg19:
		"/groups/guttman/genomes/homo_sapiens/hg19/STAR/hg19"
star_repeat_index:
	mm10:
		"/groups/guttman/Peter/genomes/ncRNA/star"
	hg19:
		"/groups/guttman/dmariani/Hs-45S"
#Annotation GTF file used for featureCounts
anno_gtf:
	mm10:
		"/groups/guttman/Peter/genomes/GRCm38.p6/GRCm38.p6.annotation.gtf.gz"
	hg19:
		"/groups/guttman/genomes/homo_sapiens/hg19/STAR/hg19/gencode.v19.annotation.gtf"
#Repeat mask used for filtering DNA contacts
mask:
	mm10:
		"/groups/guttman/Peter/genomes/GRCm38.p6/blacklist.rmsk.mm10.milliDivLessThan140.bed"
	hg19:
		"/groups/guttman/genomes/combinations/hg19_mm9/masks/hg19-mm9.gatk35-and-rmsk140.bed"
#Other indexes currently not used
bowtie2_index:
	mm10:
		"/groups/guttman/Peter/genomes/GRCm38.p6"
hisat2_index:
	mm10:
		"/groups/guttman/Peter/genomes/GRCm38.p6"



