#email to which errors will be sent
email: "pchovanec@lncrna.caltech.edu"
#Location of the config file for barcodeIdentification
bID: "./config.txt"
#Location of the samples json file produced with fastq2json.py script
samples: "/mnt/data/RNA_DNA_SPRITE/2019_09_12_NovaSeq_MegaSPRITE/samples.json"
#output directory (include trailing '/')
output_dir: "/mnt/data/RNA_DNA_SPRITE/2019_09_12_NovaSeq_MegaSPRITE/"
#Currently "mm10","hg19" and "hg38" available
assembly: "mm10"
#Number of barcodes used (this includes DPM/RPM for RNA-DNA)
num_tags: "5"
#Cell type for SNPsplit "psm44" or "psm33"
cell: "psm44"
#Run SNPsplit
snpsplit: "True"
#Annotation GTF file used for featureCounts
anno_gtf:
    mm10: "/mnt/data/genomes/GRCm38.p6/GRCm38.p6.annotation.gtf.gz"
    hg38: "/mnt/data/genomes/GRCh38/GRCh38/Homo_sapiens.GRCh38.97.gtf.gz"
#Only intron exon annotation
exon_intron_gtf:
    mm10: "/mnt/data/genomes/GRCm38.p6/GRCm38.p6.exon_intron.gtf.gz"
#Annotation GTF of rmsk repeats and tRNAs used for featureCounts
anno_repeats_gtf:
    mm10: "/mnt/data/genomes/GRCm38.p6/repeats/mm10_rmskOutCurrent.gtf.gz"
    hg38: "/mnt/data/genomes/GRCh38/repeats/hg38_rmsk.gtf.gz"
#Repeat mask used for filtering DNA contacts
mask:
    mm10: "/mnt/data/genomes/GRCm38.p6/mm10_blacklist_rmsk.milliDivLessThan140.bed"
    hg38: "/mnt/data/genomes/GRCh38/hg38_blacklist_rmsk.milliDivLessThan140.bed"
#Other indexes
bowtie2_index:
    mm10: "/mnt/data/genomes/GRCm38.p6/GRCm38.p6"
    hg38: "/mnt/data/genomes/GRCh38/GRCh38"
    psm44: "/mnt/data/genomes/GRCm38.p6/snpsplit/CAST_EiJ_129S1_SvImJ_dual_hybrid.based_on_GRCm38_N-masked/GRCm38.p6_CAST_EiJ_129S1_SvImj_N-masked"
    psm33: "/mnt/data/genomes/GRCm38.p6/snpsplit/C57BL_6NJ_129S1_SvImJ_dual_hybrid.based_on_GRCm38_N-masked/GRCm38.p6_C57BL_6NJ_129S1_SvImJ_N-masked"
bowtie2_repeat_index:
    mm10: "/mnt/data/genomes/GRCm38.p6/repeats/mm_repetitive_sequences_20200109"
hisat2_index:
    mm10: "/mnt/data/genomes/GRCm38.p6/GRCm38.p6"
    hg38: "/mnt/data/genomes/GRCh38/GRCh38"
hisat2_splice_sites:
    mm10: "/mnt/data/genomes/GRCm38.p6/Mus_musculus.GRCm38.95.ss"
    hg38: "/mnt/data/genomes/GRCh38/Homo_sapiens.GRCh38.97.ss"
snp_file:
    psm33: "/mnt/data/genomes/GRCm38.p6/snpsplit/all_129S1_SvImJ_SNPs_C57BL_6NJ_reference.based_on_GRCm38.txt"
    psm44: "/mnt/data/genomes/GRCm38.p6/snpsplit/all_129S1_SvImJ_SNPs_CAST_EiJ_reference.based_on_GRCm38.txt"
#Used for annotation of cluster file
snp_alleles:
    psm33:
        g1: "C57BL_6NJ"
        g2: "129S1_SvImJ"
    psm44:
        g1: "CAST_EiJ"
        g2: "129S1_SvImJ"
